#!/usr/bin/with-contenv bash

cd /config

if [ ! -f "$CMS_CONFIG" ]; then
    echo "Missing $CMS_CONFIG" >&2
    exit 1
fi

if [ ! -f "$CMSOCIAL_CONFIG" ]; then
    echo "Missing $CMSOCIAL_CONFIG" >&2
    exit 1
fi


exec cmsPracticeWebServer 0
